name: CICD-Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_test_typecheck:
    name: Run Tests and Qualitychecks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python and install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install -r requirements.txt || true
          pip install pylint pytest mypy black
          pip install psutil  # Installiere psutil hier zusätzlich

      - name: Install types-psutil
        run: pip install types-psutil


      - name: Check Code Style using Black
        run: |
          export PYTHONPATH=$(pwd)/Umgebung
          black --check --diff || true


      - name: Run Pylint
        run: |
                export PYTHONPATH=$(pwd)
                pylint $(pwd)/main.py || true
                pylint $(pwd)/MainHelp.py || true
                pylint $(pwd)/monitoring || true

      - name: Run mypy (Static Type Checking)
        run: |
          export PYTHONPATH=$(pwd)/Umgebung
          mypy --exclude "Alte Umgebung" . || true