name: Run Pytest & .Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: |
        python -m pytest --cov=monitoring --cov-report=html --maxfail=1 --disable-warnings -v

    - name: List htmlcov directory contents
      run: |
        if [ -d "htmlcov" ]; then ls -R htmlcov; else echo "htmlcov directory not found"; fi

    - name: Check if htmlcov has files
      run: |
        if [ "$(ls -A htmlcov)" ]; then echo "htmlcov is not empty"; else echo "htmlcov is empty"; exit 1; fi
