name: Run Pytest & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Filter requirements.txt to remove invalid lines
      run: |
        # Filter out lines that don't look like valid package names
        grep -vE '^\d{4}-\d{2}-\d{2}' requirements.txt > filtered_requirements.txt
        cat filtered_requirements.txt  # Debugging: show the filtered contents

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r filtered_requirements.txt pytest pytest-cov

    - name: Run tests
      run: |
        python -m pytest \
          --cov=monitoring \
          --cov-report=html \
          --cov-report=term \
          -v \
          --maxfail=1

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
