name: Run Pytest & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'  # Cache für schnellere Installationen

    - name: Create clean requirements.txt
      run: |
        # Lösche alle Zeilen die keine Python-Pakete sind (behält nur Zeilen die mit Buchstaben beginnen)
        grep -E '^[a-zA-Z]' requirements.txt > clean_requirements.txt
        echo "Gereinigte requirements.txt:"
        cat clean_requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r clean_requirements.txt pytest pytest-cov
        echo "Installierte Pakete:"
        pip list

    - name: Run tests with coverage
      run: |
        python -m pytest \
          --cov=monitoring \
          --cov-report=html \
          --cov-report=term \
          -v \
          --maxfail=1

    - name: Upload coverage report
      if: always()  # Hochladen auch bei Testfehlern
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/