name: Run Pytest & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        python -m pytest --cov=monitoring --cov-report=html --maxfail=1 --disable-warnings -v

    - name: Check if htmlcov directory exists
      run: |
        if [ ! -d "htmlcov" ]; then
          echo "htmlcov directory does not exist!"
          exit 1
        fi

    - name: List contents of htmlcov directory
      run: |
        ls -lR htmlcov

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v2  # Wechsel auf v2
      with:
        name: html-coverage-report
        path: htmlcov/
